# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 01:22
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170905_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('size', models.CharField(choices=[('TINY', 'VerySmall'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=50)),
                ('friendliness', models.IntegerField(validators=[api.models.validate_even])),
                ('trainability', models.IntegerField(validators=[api.models.validate_even])),
                ('sheddingamount', models.IntegerField(validators=[api.models.validate_even])),
                ('exerciseneeds', models.IntegerField(validators=[api.models.validate_even])),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age', models.CharField(max_length=5000)),
                ('gender', models.CharField(max_length=5000)),
                ('color', models.CharField(max_length=1000)),
                ('favoritefood', models.CharField(max_length=5000)),
                ('favoritetoy', models.CharField(max_length=5000)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Breed')),
            ],
        ),
    ]
